name: Elixir pre release

on:
  # Test
  pull_request:
    branches: '*'
  release:
    types: [prereleased]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install dependencies
      run:
        mix deps.get
    - name: mix release
      run: mix release
